import React from 'react';
import { CheckCircle2, XCircle, Clock, History, TrendingUp } from 'lucide-react';
import { MatchData } from '../types';

export interface PastBet {
  id: string;
  match: string;
  date: string;
  smartBet: string;
  odds: string;
  status: 'Hit' | 'Miss' | 'Pending';
  predictedScore?: string;
  confidence: number;
}

interface BetHistoryProps {
  predictions: MatchData[];
}

function buildBetsFromPredictions(predictions: MatchData[]): PastBet[] {
  return predictions.map((m, i) => {
    const { fixture, prediction } = m;
    // Derive a realistic odds string from the confidence the model gave
    const impliedProb = prediction.confidence / 100;
    const odds = (1 / impliedProb).toFixed(2);

    return {
      id: String(fixture.id ?? i),
      match: `${fixture.homeTeam.name} vs ${fixture.awayTeam.name}`,
      date: fixture.date ? new Date(fixture.date).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }) : 'Today',
      smartBet: prediction.bettingTip,
      odds,
      status: 'Pending',
      predictedScore: prediction.scoreline,
      confidence: prediction.confidence,
    };
  });
}

export default function BetHistory({ predictions }: BetHistoryProps) {
  const bets = buildBetsFromPredictions(predictions);

  const calculateWinPercentage = (bets: PastBet[]) => {
    const resolved = bets.filter((b) => b.status !== 'Pending');
    if (resolved.length === 0) return null;
    const hits = resolved.filter((b) => b.status === 'Hit').length;
    return Math.round((hits / resolved.length) * 100);
  };

  const winRate = calculateWinPercentage(bets);

  const getStatusIcon = (status: PastBet['status']) => {
    switch (status) {
      case 'Hit': return <CheckCircle2 className="text-emerald-500" size={18} />;
      case 'Miss': return <XCircle className="text-red-500" size={18} />;
      case 'Pending': return <Clock className="text-amber-500" size={18} />;
    }
  };

  const getStatusColor = (status: PastBet['status']) => {
    switch (status) {
      case 'Hit': return 'text-emerald-400 bg-emerald-500/10 border-emerald-500/20';
      case 'Miss': return 'text-red-400 bg-red-500/10 border-red-500/20';
      case 'Pending': return 'text-amber-400 bg-amber-500/10 border-amber-500/20';
    }
  };

  if (bets.length === 0) return null;

  return (
    <div className="bg-slate-900 border border-slate-700/50 rounded-2xl p-6 mb-8 relative overflow-hidden">
      {/* Decorative gradient blob */}
      <div className="absolute top-0 right-0 w-64 h-64 bg-emerald-500/5 rounded-full blur-3xl -translate-y-1/2 translate-x-1/4 pointer-events-none" />

      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-6 relative z-10">
        <div className="flex items-center gap-2">
          <div className="p-2 bg-emerald-500/10 rounded-lg">
            <History className="text-emerald-400" size={20} />
          </div>
          <div>
            <h2 className="text-xl font-bold text-white">Smart Bet History</h2>
            <p className="text-slate-500 text-xs mt-0.5">Live picks generated by our AI model — updated as results come in</p>
          </div>
        </div>

        <div className="flex items-center gap-2 bg-slate-950/50 border border-slate-800 rounded-lg px-4 py-2">
          <TrendingUp className="text-emerald-400" size={16} />
          <span className="text-slate-400 text-sm font-medium">Win Rate</span>
          <span className="text-white font-bold text-lg ml-1">
            {winRate !== null ? `${winRate}%` : '—'}
          </span>
        </div>
      </div>

      <div className="flex flex-col gap-3 relative z-10">
        {bets.map((bet) => (
          <div
            key={bet.id}
            className="bg-slate-950/50 border border-slate-800 rounded-xl p-4 flex flex-col md:flex-row md:items-center justify-between gap-4 hover:border-slate-700 transition-colors"
          >
            <div className="flex flex-col gap-1 flex-1 min-w-0">
              <div className="flex items-center gap-2 flex-wrap">
                <span className="text-white font-semibold truncate">{bet.match}</span>
                <span className="text-slate-500 text-xs whitespace-nowrap">• {bet.date}</span>
              </div>
              <div className="flex items-center gap-2 text-sm flex-wrap">
                <span className="text-slate-400">Pick:</span>
                <span className="text-slate-200 font-medium">{bet.smartBet}</span>
                <span className="text-emerald-400 font-semibold bg-emerald-500/10 px-2 py-0.5 rounded text-xs">
                  @ {bet.odds}
                </span>
                <span className="text-slate-500 text-xs">
                  Model confidence: <span className="text-slate-300">{bet.confidence}%</span>
                </span>
              </div>
            </div>

            <div className="flex items-center gap-4 shrink-0">
              {bet.predictedScore && (
                <div className="text-center hidden sm:block">
                  <span className="text-slate-500 text-xs block mb-0.5">Predicted</span>
                  <span className="text-white font-bold font-mono bg-slate-900 px-2 py-1 rounded">
                    {bet.predictedScore}
                  </span>
                </div>
              )}
              <div className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg border ${getStatusColor(bet.status)} min-w-[90px] justify-center`}>
                {getStatusIcon(bet.status)}
                <span className="text-sm font-bold tracking-wide">{bet.status}</span>
              </div>
            </div>
          </div>
        ))}
      </div>

      <p className="text-slate-600 text-xs mt-4 text-center relative z-10">
        All picks are generated in real-time by our Gemini AI model. Results updated after match completion.
      </p>
    </div>
  );
}
